### ISSUE TITLE
strange code

### ISSUE THREAD

**Issue by boris768** [emlinhax/dse_hook#1]
Always false, code above interrupts execution
https://github.com/emlinhax/dse_hook/blob/b02a24ad31673e6ac3dd4cd8c73a66ab5398e2c1/dse_hook.cpp#L171-L176

memory leak, malloc in cycle without free. Сan be replaced by an array?
https://github.com/emlinhax/dse_hook/blob/b02a24ad31673e6ac3dd4cd8c73a66ab5398e2c1/dse_hook.cpp#L185

**Comment by emlinhax** [comment]
i dont understand your first issue.
i pushed a fix for the second issue.

**Comment by boris768** [comment]
https://github.com/emlinhax/dse_hook/blob/cbc2cacdf81c8a0e9d761e0c33676a766a882c94/dse_hook.cpp#L156-L170

in this code, you either exit the program or go back to loading the driver. So one more driver_handle == -1 comparison makes no sense.
