### ISSUE TITLE
not work windows 11 23H2 build 22631.2861

### ISSUE THREAD

**Issue by l4km47** [emlinhax/dse_hook#4]
both patterns not found. how to fix it?

**Comment by emlinhax** [comment]
The answer to your question is in the question itself.

"Both patterns not found"
Solution: Update the patterns.

I dont wanna be that guy so here some more detail:
1. Open your ntoskrnl.exe in a disassembler like IDA
2. Find both functions by name (the ones named in the readme)
3. Generate new patterns for them using a plugin or by hand.
4. Profit

If you dont know how to do that, this project is not for you as it is intended for developers and researchers.
